name: Newman Test Run
on:
  push:
    branches:
    - master
    - staging
jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '18.18'
      - run:  npm install
      - run: newman run reqres.postman_collection.json -e prod.postman_environment.json -r htmlextra --reporter-htmlextra-export report.html
      
      - name: Publishing html report
        uses: actions/upload-artifact@v3
        with:
          name: html-report
          path: report.html
